### ISSUE TITLE
The player's position is not being updated correctly, and the state is not changing properly after Stop.

### ISSUE THREAD

**Issue by unseobKim** [wang-bin/fvp#116]
**Describe the bug**
I am currently using the player embedded in the FVP's mdk.dart. After connecting a local video file to the player and starting playback, I set a 10ms timer, but sometimes the position does not update and the previous position is displayed.

Additionally, the video's playback duration is up to 102910ms. After the video finishes playing and stops, the position displays as 102857, and the player's state shows as "playing."

**Expected behavior**
The current playback time of the video needs to be accurate and updated properly, and the state should also be updated accordingly.

**Log**
```
flutter: mdk.FINE: 10:39:02.211: default 0x284dcfc20 new FrameReader...
flutter: mdk.FINE: 10:39:02.212: Registered audio backends: AudioQueue OpenAL null 
flutter: mdk.FINE: 10:39:02.212: default 0x28f7c84c0 new FrameReader...
flutter: mdk.FINE: 10:39:02.212: Registered audio backends: AudioQueue OpenAL null 
flutter: mdk.FINE: 10:39:02.212: 0x13eff0f60 player.Player()
flutter: mdk.FINE: 10:39:02.212: 0x13eff0f60 player.onEvent(1, 0x16d47fdb0)
flutter: mdk.FINE: 10:39:02.212: 0x13eff0f60 player.onStateChanged(1)
flutter: mdk.FINE: 10:39:02.212: 0x13eff0f60 player.onMediaStatus(1)
flutter: mdk.FINE: 10:39:02.212: 0x13eff0f60 player.setMedia(/Users/uskim/Downloads/푸바오mp4_caption.mp4)
flutter: mdk.FINE: 10:39:02.212: default FrameReader0x284dcfc20 state: 0=>0=>0, 0
flutter: mdk.INFO: 10:39:02.212: default0x284dcfc20 stop, current state: 0
flutter: mdk.FINE: 10:39:02.213: AudioQueueStart ERROR: 0
flutter: mdk.FINE: 10:39:02.213: default FrameReader0x284dcfc20 state: 0=>0=>0, 0
flutter: mdk.INFO: 10:39:02.213: default0x284dcfc20 stop, current state: 0
flutter: mdk.FINE: 10:39:02.213: 0x13eff0f60 player.setLoop(0)
flutter: mdk.INFO: 10:39:02.213: setLoop(0), now 0/0
flutter: mdk.FINE: 10:39:02.213: 0x13eff0f60 player.setRange(0, 102910)
flutter: mdk.INFO: 10:39:02.213: setRange(0, 102910)
flutter: mdk.FINE: 10:39:02.213: 0x13eff0f60 player.prepare(0, ..., 1282)
flutter: mdk.FINE: 10:39:02.213: AudioQueueStart ERROR: 0
flutter: mdk.INFO: 10:39:02.213: 0x28e89ec00 MediaControl.prepare(0, ...) /Users/uskim/Downloads/푸바오mp4_caption.mp4
flutter: mdk.FINE: 10:39:02.214: default 0x284dcfc20 FrameReader.start(0, ...)
flutter: mdk.FINE: 10:39:02.214: default 0x284dcfc20 FrameReader::update MediaStatus 0=>0X2
flutter: mdk.FINE: 10:39:02.214: default FrameReader0x284dcfc20 state: 0=>0=>1, 0
flutter: mdk.FINE: 10:39:02.214: default FrameReader0x284dcfc20 state: 0=>1=>1, 0
flutter: mdk.FINE: 10:39:02.214: default FrameReader0x284dcfc20 request to pause 1, loaded: 0.
flutter: mdk.FINE: 10:39:02.214: default FrameReader0x284dcfc20 state: 0=>1=>2, 0
flutter: mdk.FINE: 10:39:02.214: default FrameReader0x284dcfc20 state requested: 2, current: 0
flutter: mdk.FINE: 10:39:02.214: virtual void mdk::AudioBackendAudioQueue::pause(bool)138 ERROR>>> AudioQueuePause(queue_): -50
flutter: mdk.FINE: 10:39:02.214: 
flutter: mdk.FINE: 10:39:02.214: start frame reader thread: 0x16e0ab000
flutter: mdk.FINE: 10:39:02.215: url is not supported by MediaIO FFmpeg
flutter: mdk.FINE: 10:39:02.215: url is not supported by MediaIO Mem
flutter: mdk.FINE: 10:39:02.215: Try to use default MediaIO
flutter: mdk.FINE: 10:39:02.215: 0x113092790 open url: 
flutter: mdk.FINE: 10:39:02.215: 0x113092790 url opened
flutter: mdk.FINE: 10:39:02.215: default 0x284dcfc20 FrameReader::update MediaStatus 0X2=>0X2
flutter: mdk.FINE: 10:39:02.215: 0x144aecaa0 avio set class
flutter: mdk.FINE: 10:39:02.215: before avformat_open_input. io: 0x113092790(FFmpeg)/pb: 0x144aecaa0, url: /Users/uskim/Downloads/푸바오mp4_caption.mp4
flutter: mdk.FINE: 10:39:02.216: after avformat_open_input. pb: 0x144aecaa0, iformat: 0x10a81e630, context flags: 2097280, input format flags: 67141640
flutter: mdk.INFO: 10:39:02.225: Format: mov,mp4,m4a,3gp,3g2,mj2, range: 0 +102911ms, bitrate: 752051, size: 0
Metadata:
  encoder: Lavf60.3.100
  minor_version: 512
  compatible_brands: isomiso2avc1mp41
  major_brand: isom
Streams: 2
 Video:
  stream#0, range: 0 +102891ms, frames: 3082
  codec: h264 tag: 'avc1' profile: 100 level: 31, yuv420p, bpc:8, bpp:12(8,8,8), channels:(1,1,1), map: 0 1 2 0, bitrate: 615527, 1280x720, fps: 29.954, bframes: 2, primaries: BT709, trc: BT709, matrix: BT709, range: Limited
  extra data(48): 01 64 00 1F FF E1 00 1B 67 64 00 1F AC D9 40 50 05 BB 01 6A 02 02 02 80 00 00 FA 00 00 3A 81 07 8C 18 CB 01 00 06 68 EB E3 CB 22 C0 FD F8 F8 00 
  Metadata:
   encoder: Lavc60.3.100 libx264
   handler_name: ISO Media file produced by Google Inc. Created on: 11/16/2023.
   vendor_id: [0][0][0][0]
   language: und
 Audio:
  stream#1, range: 0 +102911ms, frames: 4432
  codec: aac tag: 'mp4a' profile: 1 level: -99, sample size: 0/16, block align: 0, frame_size: 1024, f32p stereo(2) @44100Hz, bitrate: 127999
  extra data(16): 12 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  Metadata:
   handler_name: ISO Media file produced by Google Inc. Created on: 11/16/2023.
   vendor_id: [0][0][0][0]
   language: eng

flutter: mdk.FINE: 10:39:02.225: 0x28e89ec00 prepared callback is invoked
flutter: call back
flutter: mdk.FINE: 10:39:02.226: 0x13eff0f70 setRenderAPI(3, 0x0)
flutter: mdk.FINE: 10:39:02.226: getVideoOutContext 0x0 => 0x28f746950. vo count: 1
flutter: mdk.FINE: 10:39:02.227: 0x13eff0f70 setVideoSurfaceSize(1280x720, 0x0)
flutter: mdk.FINE: 10:39:02.227: default 0x284dcfc20 FrameReader::update MediaStatus 0X2=>0X4
flutter: mdk.INFO: 10:39:02.227: ***buffering progress 0%***
flutter: mdk.FINE: 10:39:02.227: default 0x284dcfc20 FrameReader::update MediaStatus 0X4=>0X14
flutter: mdk.FINE: 10:39:02.227: virtual void mdk::AudioBackendAudioQueue::pause(bool)138 ERROR>>> AudioQueuePause(queue_): -50
flutter: mdk.FINE: 10:39:02.227: 
flutter: mdk.INFO: 10:39:02.227: ++++++++++++BUFFERING START++++++++++++
flutter: mdk.FINE: 10:39:02.227: 
flutter: mdk.FINE: 10:39:02.228: default FrameReader0x284dcfc20 state: 0=>2=>1, 1
flutter: mdk.FINE: 10:39:02.228: default FrameReader0x284dcfc20 update state: 0=>1
flutter: Playback state changed from PlaybackState.stopped to PlaybackState.playing
flutter: mdk.FINE: 10:39:02.228: default FrameReader0x284dcfc20 state: 1=>1=>2, 1
flutter: mdk.FINE: 10:39:02.228: default FrameReader0x284dcfc20 update state: 1=>2
flutter: Playback state changed from PlaybackState.playing to PlaybackState.paused
flutter: mdk.FINE: 10:39:02.228: starting decode loop thread mdk.adec1@0x16e567000
flutter: mdk.FINE: 10:39:02.228: audio stream#1 starting decoding loop from decoder index 0...
flutter: mdk.FINE: 10:39:02.228: starting decode loop thread mdk.vdec0@0x16e4db000
flutter: mdk.FINE: 10:39:02.228: creating audio decoder: auto...
flutter: mdk.INFO: 10:39:02.228: opening audio decoder: FFmpeg...
flutter: mdk.FINE: 10:39:02.228: opening ffmpeg audio decoder: aac
flutter: mdk.FINE: 10:39:02.228: video stream#0 starting decoding loop from decoder index 0...
flutter: mdk.FINE: 10:39:02.229: creating video decoder: auto...
flutter: mdk.INFO: 10:39:02.229: opening video decoder: FFmpeg...
flutter: mdk.FINE: 10:39:02.229: opening ffmpeg video decoder: h264
flutter: mdk.FINE: 10:39:02.229: AVCodec.Audio[aac.] decoder: 1 Single threads
flutter: mdk.FINE: 10:39:02.229: aac f32p, stereo @44100Hz
flutter: mdk.INFO: 10:39:02.229: ***buffering progress 100%***
flutter: mdk.FINE: 10:39:02.229: default 0x284dcfc20 FrameReader::update MediaStatus 0X14=>0X124
flutter: mdk.FINE: 10:39:02.229: virtual void mdk::AudioBackendAudioQueue::pause(bool)138 ERROR>>> AudioQueuePause(queue_): -50
flutter: mdk.FINE: 10:39:02.229: 
flutter: mdk.FINE: 10:39:02.229: NALU length bytes: 4
flutter: mdk.INFO: 10:39:02.229: ++++++++++++BUFFERING END++++++++++++
flutter: mdk.FINE: 10:39:02.229: 
flutter: mdk.FINE: 10:39:02.229: audio stream#1 sending 1 invalid AOT frame @0.000000s. seeking: 0
flutter: mdk.FINE: 10:39:02.229: 0x28e89ec00 1st audio frame @0.000000
flutter: mdk.INFO: 10:39:02.230: 0x28e89ec00 seek end audio frame @0.000000 seek_pos_: -1, sync_ao_ 1
flutter: mdk.FINE: 10:39:02.230: AudioRenderer format: f32, stereo @44100Hz, requested: f32p, stereo @44100Hz
flutter: mdk.FINE: 10:39:02.230: AudioRenderer format changed and reinitialize
flutter: mdk.FINE: 10:39:02.230: AVCodec.Video[h264.] decoder: 9 Frame threads
flutter: mdk.FINE: 10:39:02.230: h264 1280x720  yuv420p
flutter: mdk.FINE: 10:39:02.230: decode stored recovery packets: 0
flutter: mdk.FINE: 10:39:02.230: h264 codec pixel format list: (expected yuv420p)
flutter: mdk.FINE: 10:39:02.231: videotoolbox_vld
flutter: mdk.FINE: 10:39:02.231: yuv420p (selected)
flutter: mdk.FINE: 10:39:02.231: yuv420p using avcodec software decoder...
flutter: mdk.FINE: 10:39:02.240: video stream#0 sending 1 invalid AOT frame @0.000000s. seeking: 0
flutter: mdk.FINE: 10:39:02.240: 0x28e89ec00 1st video frame to render @0.000000s, sync time: -0.001000
flutter: mdk.FINE: 10:39:02.240: VideoRenderer clear buffered frames
flutter: mdk.FINE: 10:39:02.240: 0-track seek end video frame @0.000000 seek_pos_: -1
flutter: mdk.FINE: 10:39:02.240: 0x28e89ec00 1st video frame to render @0.000000s, sync time: -0.001000
flutter: mdk.FINE: 10:39:02.240: VideoRenderer WxH=1280.000000x720.000000 1280.000000x720.000000, frame: 1280x720
flutter: mdk.FINE: 10:39:02.240: update transform 2d. scale: (1.000000, 1.000000), orientation: 0
flutter: mdk.FINE: 10:39:02.240: m: mat<4, 4>(
flutter: mdk.FINE: 10:39:02.240: 1  0  0  0  
flutter: mdk.FINE: 10:39:02.240: 0  1  0  0  
flutter: mdk.FINE: 10:39:02.240: 0  0  1  0  
flutter: mdk.FINE: 10:39:02.241: 0  0  0  1 
flutter: mdk.FINE: 10:39:02.241: )
flutter: mdk.FINE: 10:39:02.241: Metal pixel format 0: MTLPixelFormatR8Unorm, size: 1280x720
flutter: mdk.FINE: 10:39:02.241: 
flutter: mdk.FINE: 10:39:02.241: Metal pixel format 1: MTLPixelFormatR8Unorm, size: 640x360
flutter: mdk.FINE: 10:39:02.241: 
flutter: mdk.FINE: 10:39:02.241: Metal pixel format 2: MTLPixelFormatR8Unorm, size: 640x360
flutter: mdk.FINE: 10:39:02.241: 
flutter: mdk.FINE: 10:39:02.241: channel map: mat<4, 4>(
flutter: mdk.FINE: 10:39:02.241: 1  0  0  0  
flutter: mdk.FINE: 10:39:02.241: 0  1  0  0  
flutter: mdk.FINE: 10:39:02.241: 0  0  1  0  
flutter: mdk.FINE: 10:39:02.241: 0  0  0  1  
flutter: mdk.FINE: 10:39:02.241: )
flutter: mdk.FINE: 10:39:02.241: frame format: yuv420p, bpc:8, bpp:12(8,8,8), channels:(1,1,1), map: 0 1 2 0
flutter: mdk.FINE: 10:39:02.241: frame color: BT709 BT709 BT709 Limited. gamma: 2.200000, signal peak: 1.000000
flutter: mdk.FINE: 10:39:02.241:  - 
flutter: mdk.FINE: 10:39:02.241: output color: BT709 UNSPECIFIED RGB Full. gamma: 2.200000, signal peak: 1.000000
flutter: mdk.FINE: 10:39:02.241: rgb primaries matrix: mat<3, 3>(
flutter: mdk.FINE: 10:39:02.241: 1  0  0  
flutter: mdk.FINE: 10:39:02.242: 0  1  0  
flutter: mdk.FINE: 10:39:02.242: 0  0  1  
flutter: mdk.FINE: 10:39:02.242: )
flutter: mdk.FINE: 10:39:02.242: scale: 1.000000, color transform: mat<4, 4>(
flutter: mdk.FINE: 10:39:02.242: 1.16438  0  1.79274  -0.972945  
flutter: mdk.FINE: 10:39:02.242: 1.16438  -0.213249  -0.532909  0.301483  
flutter: mdk.FINE: 10:39:02.242: 1.16438  2.1124  0  -1.1334  
flutter: mdk.FINE: 10:39:02.242: 0  0  0  1  
flutter: mdk.FINE: 10:39:02.242: )
flutter: mdk.FINE: 10:39:02.242: EQ: mat<4, 4>(
flutter: mdk.FINE: 10:39:02.242: 1  0  0  0  
flutter: mdk.FINE: 10:39:02.242: 0  1  0  0  
flutter: mdk.FINE: 10:39:02.242: 0  0  1  0  
flutter: mdk.FINE: 10:39:02.242: 0  0  0  1  
flutter: mdk.FINE: 10:39:02.242: )
flutter: mdk.FINE: 10:39:02.242: shader id: 2305
flutter: mdk.FINE: 10:39:02.242: dump UBO layout:
align @offset +size /stride address name ~ path: type -> parent
16@0 +64/16 0x284dffd38 u_colorMatrix ~ u_colorMatrix: mat4 -> 0x0            

flutter: mdk.FINE: 10:39:02.271: Using audio backend: AudioQueue
flutter: mdk.FINE: 10:39:02.304: 0x28e89ec00 ao opened: 1, reopen: 1, bad ao: 0. valid: 0
flutter: mdk.FINE: 10:41:09.477: 0x13eff0f60 player.set(1)
flutter: mdk.FINE: 10:41:09.477: 0x28e89ec00 virtual void mdk::MediaControlPush::setState(PlaybackState)@1068 requested state 2=>1, current state 2. status: 0X124
flutter: player 1 Position : 80
flutter: mdk.FINE: 10:41:09.478: default FrameReader0x284dcfc20 request to pause 0, loaded: 4.
flutter: mdk.FINE: 10:41:09.478: default FrameReader0x284dcfc20 state: 2=>2=>1, 0
flutter: mdk.FINE: 10:41:09.478: default FrameReader0x284dcfc20 state requested: 1, current: 2
flutter: mdk.FINE: 10:41:09.478: video stream#0 AOT frame is sent
flutter: mdk.FINE: 10:41:09.478: default FrameReader0x284dcfc20 state: 2=>1=>1, 1
flutter: mdk.FINE: 10:41:09.478: default FrameReader0x284dcfc20 update state: 2=>1
flutter: Playback state changed from PlaybackState.paused to PlaybackState.playing
flutter: mdk.FINE: 10:41:09.482: 0x11ee512d8 filter graph: 
flutter: mdk.FINE: 10:41:09.482: +-----------+
|    src    |default--[44100Hz fltp:stereo]--swr:default
| (abuffer) |
+-----------+

                                          +---------------+
swr:default--[44100Hz flt:stereo]--default|      dst      |
                                          | (abuffersink) |
                                          +---------------+

                                           +-------------+
src:default--[44100Hz fltp:stereo]--default|     swr     |default--[44100Hz flt:stereo]--dst:default
                                           | (aresample) |
                                           +-------------+
2

flutter: mdk.FINE: 10:41:09.483: >>>>>>>>1st audio frame (after seek) rendered: 1, ao: 15, a: 0, delta: 15 +0.023220
flutter: mdk.FINE: 10:41:09.483: audio stream#1 AOT frame is sent
2
flutter: player 1 Position : 33
flutter: player 1 Position : 43
flutter: player 1 Position : 56
flutter: player 1 Position : 66
flutter: player 1 Position : 79
flutter: player 1 Position : 88
flutter: player 1 Position : 101
flutter: player 1 Position : 112
flutter: player 1 Position : 123
flutter: player 1 Position : 133
flutter: player 1 Position : 145
flutter: player 1 Position : 149
flutter: player 1 Position : 157
flutter: player 1 Position : 159
flutter: player 1 Position : 172
flutter: player 1 Position : 182
flutter: player 1 Position : 200
flutter: player 1 Position : 213
flutter: player 1 Position : 218
flutter: player 1 Position : 228
flutter: player 1 Position : 242
flutter: player 1 Position : 251
flutter: player 1 Position : 267
flutter: player 1 Position : 274
flutter: player 1 Position : 275
flutter: player 1 Position : 285
flutter: player 1 Position : 295
flutter: player 1 Position : 310
flutter: player 1 Position : 316
flutter: player 1 Position : 321
flutter: player 1 Position : 335
flutter: player 1 Position : 345
flutter: player 1 Position : 358
flutter: player 1 Position : 368
flutter: player 1 Position : 381
flutter: player 1 Position : 391
2
flutter: player 1 Position : 404
flutter: player 1 Position : 413
flutter: player 1 Position : 426
flutter: player 1 Position : 435
flutter: player 1 Position : 448
flutter: player 1 Position : 461
flutter: player 1 Position : 470
flutter: player 1 Position : 474
flutter: player 1 Position : 484
flutter: player 1 Position : 500
flutter: player 1 Position : 516
flutter: player 1 Position : 520
flutter: player 1 Position : 534
2
flutter: player 1 Position : 544
flutter: player 1 Position : 554

------------------------------------ 여기부터 stop 이후 playing 들어오는거



flutter: mdk.INFO: 10:46:38.148: video stream#0 EOF/EOS decoded. end: 1
flutter: player 1 Position : 102525
flutter: player 1 Position : 102526
flutter: player 1 Position : 102533
flutter: player 1 Position : 102545
flutter: player 1 Position : 102555
flutter: player 1 Position : 102568
flutter: player 1 Position : 102572
flutter: player 1 Position : 102582
flutter: player 1 Position : 102595
flutter: player 1 Position : 102605
flutter: player 1 Position : 102618
flutter: player 1 Position : 102628
flutter: player 1 Position : 102642
flutter: player 1 Position : 102652
flutter: player 1 Position : 102663
flutter: player 1 Position : 102665
flutter: player 1 Position : 102672
flutter: player 1 Position : 102685
flutter: player 1 Position : 102694
flutter: player 1 Position : 102707
flutter: player 1 Position : 102718
flutter: player 1 Position : 102731
flutter: player 1 Position : 102735
flutter: player 1 Position : 102745
flutter: player 1 Position : 102758
flutter: player 1 Position : 102768
flutter: player 1 Position : 102781
2
flutter: player 1 Position : 102791
flutter: player 1 Position : 102804
flutter: player 1 Position : 102814
flutter: player 1 Position : 102826
flutter: player 1 Position : 102835
flutter: player 1 Position : 102849
flutter: player 1 Position : 102858
flutter: mdk.FINE: 10:46:38.487: video stream#0 check loop range for EOS. dec_state.seeking: 0. end: 1, nb_decoded:487
flutter: mdk.FINE: 10:46:38.487: 0x28e90d000 track#0: no more range loop. loop 0/0.
flutter: mdk.FINE: 10:46:38.487: default FrameReader0x284dd7e10 video stream#0 range loop end
flutter: mdk.FINE: 10:46:38.487: EOS video frame of track 0
flutter: mdk.FINE: 10:46:38.489: 0x284dd7e10 #video stream#0 end semaphore done acquire
flutter: mdk.FINE: 10:46:38.489: 0x284dd7e10 #audio stream#1 end semaphore acquire
flutter: mdk.FINE: 10:46:38.489: VideoFrame8009@179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000 to be destroyed is not rendered by  0x2810765700x284dd7e10 #audio stream#1 end semaphore done acquire
flutter: mdk.FINE: 10:46:38.489: EOS video frame of track 0
flutter: mdk.FINE: 10:46:38.489: 
flutter: mdk.FINE: 10:46:38.489: 0x284dd7e10 #video stream#0 end semaphore acquire
flutter: mdk.FINE: 10:46:38.489: video stream#0 decoding loop is finished. packets: 1, pts: [0.000000, 0.000000]
flutter: mdk.FINE: 10:46:38.489: 0x284dd7e10 #video stream#0 end semaphore done acquire
flutter: mdk.FINE: 10:46:38.489: 0x284dd7e10 #audio stream#1 end semaphore acquire
flutter: player 1 Position : 102871
flutter: player 1 Position : 102880
flutter: player 1 Position : 102884
flutter: player 1 Position : 102897
flutter: mdk.INFO: 10:46:38.531: audio stream#1 EOF/EOS decoded. end: 1
flutter: mdk.FINE: 10:46:38.531: audio stream#1 check loop range for EOS. dec_state.seeking: 0. end: 1, nb_decoded:702
flutter: mdk.FINE: 10:46:38.531: 0x28e90d000 track#1: no more range loop. loop 0/0.
flutter: mdk.FINE: 10:46:38.531: default FrameReader0x284dd7e10 audio stream#1 range loop end
2
flutter: mdk.FINE: 10:46:38.531: EOS audio frame of track 0
flutter: mdk.FINE: 10:46:38.531: 0x284dd7e10 #audio stream#1 end semaphore done acquire
flutter: mdk.FINE: 10:46:38.531: audio stream#1 decoding loop is finished. packets: 1, pts: [0.000000, 0.000000]
flutter: mdk.FINE: 10:46:38.531: 0x284dd7e10 #video stream#0 end semaphore acquire
flutter: mdk.FINE: 10:46:38.531: 0x284dd7e10 #video stream#0 end semaphore done acquire
flutter: mdk.FINE: 10:46:38.531: 0x284dd7e10 #audio stream#1 end semaphore acquire
flutter: mdk.FINE: 10:46:38.531: 0x284dd7e10 #audio stream#1 end semaphore done acquire
flutter: mdk.FINE: 10:46:38.531: before changed() 164
flutter: mdk.FINE: 10:46:38.532: default FrameReader0x284dd7e10 state: 1=>1=>0, 0
flutter: mdk.FINE: 10:46:38.532: 0x284dd7e10 unload, current status 0x164, invalid: 0, loading: 0, loaded: 4, buffering: 0, seeking: 0, prepared: 256, EOF: 64
flutter: mdk.FINE: 10:46:38.532: 0x13ee6d5b8 request avformat input interrupt
flutter: mdk.FINE: 10:46:38.532: 0x11308fcb8 request to interrupt io operation
flutter: mdk.FINE: 10:46:38.532: free custome avio: 0x1130e4d30
flutter: mdk.FINE: 10:46:38.532: 0x11308fc90 close url: /Users/uskim/Downloads/푸바오mp4_caption.mp4
flutter: mdk.FINE: 10:46:38.532: 0x288e9f000default 0x284dd7e10 update @1149: reset status_mask. status: 161
flutter: mdk.FINE: 10:46:38.532: default 0x284dd7e10 FrameReader::update MediaStatus 0X164=>0X41
flutter: mdk.FINE: 10:46:38.532: default FrameReader0x284dd7e10 state: 1=>0=>0, 1
flutter: mdk.FINE: 10:46:38.532: default FrameReader0x284dd7e10 update state: 1=>0
flutter: Playback state changed from PlaybackState.playing to PlaybackState.stopped
flutter: stop to play
flutter: stop state : PlaybackState.playing
flutter: player 1 Position : 102857
flutter: stop state : PlaybackState.playing
flutter: player 1 Position : 102857
flutter: stop state : PlaybackState.playing
```

**Comment by wang-bin** [comment]
try master branch. previously it the value set by user

**Comment by wang-bin** [comment]
btw, it's better to set `player.videoDecoders = ['VT', 'FFmpeg'];` to enable hardware decoder

**Comment by unseobKim** [comment]
> try master branch. previously it the value set by user

Are you asking me to directly receive the code and import it instead of adding it to the dependencies?

**Comment by wang-bin** [comment]
no
```yaml
 fvp:
    git:
      url: https://github.com/wang-bin/fvp
```

If master branch works, I will make a new release later
