### ISSUE TITLE
Integration tests do not run under linux github action runners

### ISSUE THREAD

**Issue by Bonfra04** [wang-bin/fvp#212]
**Describe the bug**

Running an integration test under a github action fails for linux platform. Specifically during the plugin initialization phase while the specified `pluginClass: FvpPlugin` is loaded.

**Expected behavior**

Integration tests starts correctly

**Steps to reproduce**
- add a file in `example\integration_test\app_test.dart` with a minimal test
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

void main() async {
    IntegrationTestWidgetsFlutterBinding.ensureInitialized();

    test("3+3", () {
        expect(3 + 3, 6);
    });
}
```
- add a minimal github workflow file that invokes this test
```yml
name: Integration Tests Linux

on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@main
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: sudo apt-get update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
      - name: install deps
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
      - run: sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - run: "cd example && DISPLAY=:99 flutter test -d linux integration_test/app_test.dart"
```
- run the action

**Log**
```
✓ Built build/linux/x64/debug/bundle/fvp_example
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
❌ loading /home/runner/work/fvp/fvp/example/integration_test/app_test.dart (failed)
  Failed to load "/home/runner/work/fvp/fvp/example/integration_test/app_test.dart": Unable to start the app on the device.
  package:flutter_tools/src/test/integration_test_device.dart 63:86  IntegrationTestTestDevice.start
  ===== asynchronous gap ===========================
  package:flutter_tools/src/test/flutter_platform.dart 5[46](https://github.com/Bonfra04/fvp/actions/runs/12961234260/job/36156239626#step:7:47):49        FlutterPlatform._startTest.<fn>
  ===== asynchronous gap ===========================
  package:flutter_tools/src/base/async_guard.dart 111:24             asyncGuard.<fn>
```

**Added context**
Since this action runs specifically under Linux, I tried commenting out the line in the library's pubspec file that specifies the native class to invoke, and the test has run successfully.
you can take a look at [my fork](https://github.com/Bonfra04/fvp/) for a minimal example.

I tried googling the error around but the only related results lead to [this issue](https://github.com/flutter/flutter/issues/101031) which is not relevant, or to some StackOverflow questions that just get resolved by adding Xvfb as a virtual display manager.

Sadly I couldn't replicate the issue on my local machine. Meaning i tried running a headless tty and starting the test with Xvfb; it worked just fine so the only lab i can 100% say this issue arise is in the github action runners

**Comment by Bonfra04** [comment]
After  bit more digging, it turns out that the main problem was that the ubuntu runner does not have `libpulse0` preinstalled which is a dependency for `fvp`.  Adding it via apt makes the test succeed.
I know it should come preinstalled in most distros but since the error message is so cryptic it could be considered to add it to some sort of dependency section in the readme of the repo.

Solved this first issue another one arise that takes place while trying to launch the application for the tests:

```
✓ Built build/linux/x64/debug/bundle/MyApp

(MyApp:5278): Gtk-WARNING **: 11:24:04.902: cannot open display: 
0.30.1 (git 7556ef4) - Multimedia Development Kit. Copyright (c) 2016-2025 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Linux 4KB x86_64; glibc2.24/2.39 libc++200000; Clang20.0.0 (++20250124081700+bfd9bc274586-1~exp1~20250124081833.684); 07:57:02 Jan 25 2025
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
Error launching application on Linux.
```
It should be able to open the virtual display provided by Xvfb or in general to start the app

**Comment by Bonfra04** [comment]
A bit more debugging later...
```
  test_linux:
    runs-on: ubuntu-latest

    env:
      LIBGL_ALWAYS_SOFTWARE: 1
      DISPLAY: :99

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libpulse0 libglu1-mesa at-spi2-core pulseaudio

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
          channel: "stable"
          architecture: x64

      - name: Run tests
        run: |
          systemctl --user start pulseaudio.service 
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          DISPLAY=:99 flutter run -d linux
```
these four packages needs to be present on the runner `libpulse0 libglu1-mesa at-spi2-core pulseaudio` and pulse audio needs to be running ` systemctl --user start pulseaudio.service `. This configuration fixes the issue on the github runner
